name: Update site

on:
  schedule:
    - cron: "* 0 * * *"
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v4
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.x'
    # - name: Install Poetry
    #   run: |
    #     pip install poetry
    # - name: Install dependencies
    #   run: |
    #     poetry install
    # - name: Run parser
    #   run: |
    #     export GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
    #     poetry run python parse.py
    # - uses: r-lib/actions/setup-r@v2
    #   with:
    #     r-version: '4.2.0' # The R version to download (if necessary) and use.
    # - uses: r-lib/actions/setup-renv@v2
    #   with:
    #     cache-version: 1
    # - uses: r-lib/actions/setup-r-dependencies@v2
    #   with:
    #     packages:
    #       any::knitr
    #       any::rmarkdown
    #       any::downlit
    #       any::xml2
    #       any::tidyverse
    #       any::DT
    # - name: Run quarto render
    #   run: |
    #     quarto render .
    # - name: Deploy pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./docs
    - name: setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.4.550
    # - uses: r-lib/actions/setup-r@v2
    #   with:
    #     r-version: '4.2.0' # The R version to download (if necessary) and use.
    # - uses: r-lib/actions/setup-r-dependencies@v2
    #   with:
    #     packages:
    #       any::knitr
    #       any::rmarkdown
    #       any::downlit
    #       any::xml2
    #       any::tidyverse
    #       any::DT
    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
      with:
        path: ./site
    - name: Deploy pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/docs
